host: 'localhost'
port: 8848
namespace: 'd0850b97-9af8-4508-b733-801d392b35ba'
user: 'nacos'
password: 'nacos'
dataid: 'goods-web.json'
group: 'dev'

#goods_srv:
#  host: 'localhost'
#  port: 50051
#  name: 'usr-srv'
#jwt:
#  key:
#sms:
#  key: 'LTAI5tDqXNYpkC5uGrQwznXu'
#  secrect: 'muegZ80p0ewcdkrFDzWLaM0xBxUxeB'
#  expire: 300
#
#redis:
#  host: '192.168.181.129'
#  port: 6379
#
#consul:
#  host: '192.168.181.129'
#  port: 8500
