host: 'localhost'
port: 8848
namespace: 'c1872978-d51c-4188-a497-4e0cd20b97d5'
user: 'nacos'
password: 'nacos'
dataid: 'user-web.json'
group: 'dev'

#user_srv:
#  host: 'localhost'
#  port: 50051
#  name: 'usr-srv'
#jwt:
#  key:
#sms:
#  key: 'LTAI5tDqXNYpkC5uGrQwznXu'
#  secrect: 'muegZ80p0ewcdkrFDzWLaM0xBxUxeB'
#  expire: 300
#
#redis:
#  host: '192.168.181.129'
#  port: 6379
#
#consul:
#  host: '192.168.181.129'
#  port: 8500
