host: 'localhost'
port: 8848
namespace: 'c1872978-d51c-4188-a497-4e0cd20b97d5'
user: 'nacos'
password: 'nacos'
dataid: 'user-web.json'
group: 'pro'

#user_srv:
#  host: 'localhost'
#  port: 50051
#  name: 'usr-srv'
#jwt:
#  key:
#sms:
<<<<<<< HEAD
#  key:
#  secrect:
=======
#  key: 
#  secrect: 
>>>>>>> 63be52a3cb125d5af1152168247f17adb9011b62
#  expire: 300
#
#redis:
#  host: '192.168.181.129'
#  port: 6379
#
#consul:
#  host: '192.168.181.130'
#  port: 8500
